"""Default config writer and read helpers for AgentTower."""

from __future__ import annotations

import errno
import os
import stat
from pathlib import Path

DEFAULT_CONFIG_TOML = """\
# AgentTower configuration
# Generated by `agenttower config init`. Edit freely; subsequent
# `config init` runs will not overwrite this file.

[containers]
name_contains = ["bench"]
scan_interval_seconds = 5
"""

_FILE_MODE = 0o600
_DIR_MODE = 0o700


def _render_default_config() -> str:
    return DEFAULT_CONFIG_TOML


def _ensure_dir_chain(target: Path, *, namespace_root: Path) -> None:
    """Create every missing dir from namespace_root up to target with mode 0700.

    Pre-existing directories at or under namespace_root that have a broader
    mode than 0o700 cause an OSError with errno EPERM. Pre-existing dirs
    outside namespace_root are not mode-checked (they may pre-date AgentTower).
    """
    if target.exists():
        _verify_dir_mode_under_namespace(target, namespace_root=namespace_root)
        return

    parent = target.parent
    if not parent.exists():
        _ensure_dir_chain(parent, namespace_root=namespace_root)
    elif _is_under(parent, namespace_root):
        _verify_dir_mode_under_namespace(parent, namespace_root=namespace_root)

    target.mkdir(mode=_DIR_MODE, exist_ok=False)
    os.chmod(target, _DIR_MODE)


def _is_under(path: Path, root: Path) -> bool:
    try:
        path.resolve().relative_to(root.resolve())
        return True
    except ValueError:
        return False


def _verify_dir_mode_under_namespace(path: Path, *, namespace_root: Path) -> None:
    if not _is_under(path, namespace_root) and path != namespace_root:
        return
    actual = stat.S_IMODE(os.stat(path).st_mode)
    if actual & ~_DIR_MODE:
        raise OSError(
            errno.EPERM,
            f"directory mode {oct(actual)} broader than required {oct(_DIR_MODE)}",
            str(path),
        )


def _verify_file_mode(path: Path, required: int) -> None:
    actual = stat.S_IMODE(os.stat(path).st_mode)
    if actual & ~required:
        raise OSError(
            errno.EPERM,
            f"file mode {oct(actual)} broader than required {oct(required)}",
            str(path),
        )


def write_default_config(config_file: Path, *, namespace_root: Path | None = None) -> str:
    """Write the default config at *config_file* if absent.

    Returns ``"created"`` when this call wrote the file, ``"already initialized"``
    when it was already present (and had an acceptable mode).
    Raises ``OSError`` on filesystem errors or pre-existing weak modes.
    """
    if namespace_root is None:
        namespace_root = config_file.parent

    _ensure_dir_chain(config_file.parent, namespace_root=namespace_root)

    if config_file.exists():
        _verify_file_mode(config_file, _FILE_MODE)
        return "already initialized"

    flags = os.O_WRONLY | os.O_CREAT | os.O_EXCL
    fd = os.open(config_file, flags, _FILE_MODE)
    try:
        os.write(fd, _render_default_config().encode("utf-8"))
        os.fchmod(fd, _FILE_MODE)
    finally:
        os.close(fd)
    return "created"
