"""Default config writer and read helpers for AgentTower."""

from __future__ import annotations

import errno
import os
import stat
import tomllib
from dataclasses import dataclass
from pathlib import Path

DEFAULT_CONFIG_TOML = """\
# AgentTower configuration
# Generated by `agenttower config init`. Edit freely; subsequent
# `config init` runs will not overwrite this file.

[containers]
name_contains = ["bench"]
scan_interval_seconds = 5
"""

_FILE_MODE = 0o600
_DIR_MODE = 0o700


class ConfigInvalidError(Exception):
    """Raised when the on-disk config violates FEAT-003 validation rules."""

    def __init__(self, message: str) -> None:
        super().__init__(message)
        self.message = message


def _render_default_config() -> str:
    return DEFAULT_CONFIG_TOML


def _ensure_dir_chain(target: Path, *, namespace_root: Path) -> None:
    """Create every missing dir from namespace_root up to target with mode 0700.

    Pre-existing directories at or under namespace_root that have a broader
    mode than 0o700 cause an OSError with errno EPERM. Pre-existing dirs
    outside namespace_root are not mode-checked (they may pre-date AgentTower).
    """
    if target.exists():
        _verify_dir_mode_under_namespace(target, namespace_root=namespace_root)
        return

    parent = target.parent
    if not parent.exists():
        _ensure_dir_chain(parent, namespace_root=namespace_root)
    elif _is_under(parent, namespace_root):
        _verify_dir_mode_under_namespace(parent, namespace_root=namespace_root)

    target.mkdir(mode=_DIR_MODE, exist_ok=False)
    os.chmod(target, _DIR_MODE)


def _is_under(path: Path, root: Path) -> bool:
    try:
        path.resolve().relative_to(root.resolve())
        return True
    except ValueError:
        return False


def _verify_dir_mode_under_namespace(path: Path, *, namespace_root: Path) -> None:
    if not _is_under(path, namespace_root) and path != namespace_root:
        return
    actual = stat.S_IMODE(os.stat(path).st_mode)
    if actual & ~_DIR_MODE:
        raise OSError(
            errno.EPERM,
            f"directory mode {oct(actual)} broader than required {oct(_DIR_MODE)}",
            str(path),
        )


def _verify_file_mode(path: Path, required: int) -> None:
    actual = stat.S_IMODE(os.stat(path).st_mode)
    if actual & ~required:
        raise OSError(
            errno.EPERM,
            f"file mode {oct(actual)} broader than required {oct(required)}",
            str(path),
        )


_MAX_NAME_CONTAINS_ENTRIES = 32
_MAX_NAME_CONTAINS_LENGTH = 128
_MAX_ERROR_MSG = 2048


def _bound(text: str) -> str:
    cleaned = "".join(ch for ch in text if ch == "\t" or ch == "\n" or ord(ch) >= 32)
    return cleaned[:_MAX_ERROR_MSG]


def load_containers_block(config_path: Path):
    """Load and validate `[containers] name_contains` from *config_path*.

    Returns a `MatchingRule`. Raises :class:`ConfigInvalidError` per
    FR-006 / FR-030 when the block is malformed. A missing block (or a
    missing `name_contains` key) yields the default rule (FR-005).
    """
    # Local import keeps `agenttower.config` importable without the
    # `agenttower.discovery` subpackage being available at import time.
    from .discovery.matching import MatchingRule, default_rule

    if not config_path.exists():
        return default_rule()

    try:
        with open(config_path, "rb") as fh:
            data = tomllib.load(fh)
    except (OSError, tomllib.TOMLDecodeError) as exc:
        raise ConfigInvalidError(_bound(f"failed to parse {config_path}: {exc}")) from exc

    block = data.get("containers")
    if block is None:
        return default_rule()
    if not isinstance(block, dict):
        raise ConfigInvalidError(
            _bound(f"[containers] must be a TOML table; got {type(block).__name__}")
        )

    if "name_contains" not in block:
        return default_rule()

    raw = block["name_contains"]
    if not isinstance(raw, list):
        raise ConfigInvalidError(
            _bound(
                f"[containers] name_contains must be a list of strings; got "
                f"{raw!r} ({type(raw).__name__})"
            )
        )
    if len(raw) == 0:
        raise ConfigInvalidError(
            "[containers] name_contains must be a non-empty list of non-empty strings; got []"
        )
    if len(raw) > _MAX_NAME_CONTAINS_ENTRIES:
        raise ConfigInvalidError(
            _bound(
                f"[containers] name_contains has {len(raw)} entries; max is "
                f"{_MAX_NAME_CONTAINS_ENTRIES}"
            )
        )

    cleaned: list[str] = []
    for index, entry in enumerate(raw):
        if not isinstance(entry, str):
            raise ConfigInvalidError(
                _bound(
                    f"[containers] name_contains[{index}] must be a string; "
                    f"got {entry!r} ({type(entry).__name__})"
                )
            )
        if len(entry) > _MAX_NAME_CONTAINS_LENGTH:
            raise ConfigInvalidError(
                _bound(
                    f"[containers] name_contains[{index}] is {len(entry)} chars; "
                    f"max is {_MAX_NAME_CONTAINS_LENGTH}; value={entry!r}"
                )
            )
        stripped = entry.strip()
        if not stripped:
            raise ConfigInvalidError(
                _bound(
                    f"[containers] name_contains[{index}] is blank after strip(); "
                    f"originally {entry!r}"
                )
            )
        cleaned.append(stripped)

    return MatchingRule(name_contains=tuple(cleaned))


@dataclass(frozen=True)
class EventsConfig:
    """Resolved FEAT-008 ``[events]`` configuration block.

    All fields default to the constants in
    ``agenttower.events.__init__`` (FR-045 / Plan §"Defaults locked").
    Values come from the ``[events]`` table in ``config.toml`` when
    present; missing keys fall back to the defaults.
    """

    reader_cycle_wallclock_cap_seconds: float
    per_cycle_byte_cap_bytes: int
    per_event_excerpt_cap_bytes: int
    excerpt_truncation_marker: str
    debounce_activity_window_seconds: float
    pane_exited_grace_seconds: float
    long_running_grace_seconds: float
    default_page_size: int
    max_page_size: int
    follow_long_poll_max_seconds: float
    follow_session_idle_timeout_seconds: float


def _events_defaults() -> "EventsConfig":
    """Return the FR-045 defaults from ``agenttower.events``."""

    from . import events as _events

    return EventsConfig(
        reader_cycle_wallclock_cap_seconds=_events.READER_CYCLE_WALLCLOCK_CAP_SECONDS,
        per_cycle_byte_cap_bytes=_events.PER_CYCLE_BYTE_CAP_BYTES,
        per_event_excerpt_cap_bytes=_events.PER_EVENT_EXCERPT_CAP_BYTES,
        excerpt_truncation_marker=_events.EXCERPT_TRUNCATION_MARKER,
        debounce_activity_window_seconds=_events.DEBOUNCE_ACTIVITY_WINDOW_SECONDS,
        pane_exited_grace_seconds=_events.PANE_EXITED_GRACE_SECONDS,
        long_running_grace_seconds=_events.LONG_RUNNING_GRACE_SECONDS,
        default_page_size=_events.DEFAULT_PAGE_SIZE,
        max_page_size=_events.MAX_PAGE_SIZE,
        follow_long_poll_max_seconds=_events.FOLLOW_LONG_POLL_MAX_SECONDS,
        follow_session_idle_timeout_seconds=_events.FOLLOW_SESSION_IDLE_TIMEOUT_SECONDS,
    )


_EVENTS_FLOAT_KEYS = {
    "reader_cycle_wallclock_cap_seconds",
    "debounce_activity_window_seconds",
    "pane_exited_grace_seconds",
    "long_running_grace_seconds",
    "follow_long_poll_max_seconds",
    "follow_session_idle_timeout_seconds",
}
_EVENTS_INT_KEYS = {
    "per_cycle_byte_cap_bytes",
    "per_event_excerpt_cap_bytes",
    "default_page_size",
    "max_page_size",
}
_EVENTS_STR_KEYS = {"excerpt_truncation_marker"}


def load_events_block(config_path: Path) -> EventsConfig:
    """Load and validate ``[events]`` from *config_path*.

    Missing file, missing block, or missing key falls back to the
    FR-045 defaults. Type errors and out-of-range values raise
    :class:`ConfigInvalidError`.
    """

    defaults = _events_defaults()
    if not config_path.exists():
        return defaults

    try:
        with open(config_path, "rb") as fh:
            data = tomllib.load(fh)
    except (OSError, tomllib.TOMLDecodeError) as exc:
        raise ConfigInvalidError(_bound(f"failed to parse {config_path}: {exc}")) from exc

    block = data.get("events")
    if block is None:
        return defaults
    if not isinstance(block, dict):
        raise ConfigInvalidError(
            _bound(f"[events] must be a TOML table; got {type(block).__name__}")
        )

    overrides: dict[str, object] = {}
    for key, raw in block.items():
        if key in _EVENTS_FLOAT_KEYS:
            if not isinstance(raw, (int, float)) or isinstance(raw, bool):
                raise ConfigInvalidError(
                    _bound(f"[events] {key} must be a number; got {raw!r}")
                )
            value = float(raw)
            if value <= 0:
                raise ConfigInvalidError(
                    _bound(f"[events] {key} must be > 0; got {value}")
                )
            overrides[key] = value
        elif key in _EVENTS_INT_KEYS:
            if not isinstance(raw, int) or isinstance(raw, bool):
                raise ConfigInvalidError(
                    _bound(f"[events] {key} must be an integer; got {raw!r}")
                )
            if raw <= 0:
                raise ConfigInvalidError(
                    _bound(f"[events] {key} must be > 0; got {raw}")
                )
            overrides[key] = raw
        elif key in _EVENTS_STR_KEYS:
            if not isinstance(raw, str):
                raise ConfigInvalidError(
                    _bound(f"[events] {key} must be a string; got {raw!r}")
                )
            overrides[key] = raw
        else:
            raise ConfigInvalidError(
                _bound(f"[events] unknown key {key!r}")
            )

    # Apply MVP caps named in FR-014 (≤ 5 s), FR-017 (≤ 30 s), FR-030
    # (≤ 50 page size). Values exceeding the caps are rejected; values
    # equal to the caps are accepted.
    if overrides.get("debounce_activity_window_seconds", defaults.debounce_activity_window_seconds) > 5.0:
        raise ConfigInvalidError(
            _bound(
                "[events] debounce_activity_window_seconds must be ≤ 5.0 (FR-014); "
                f"got {overrides['debounce_activity_window_seconds']}"
            )
        )
    if overrides.get("pane_exited_grace_seconds", defaults.pane_exited_grace_seconds) > 30.0:
        raise ConfigInvalidError(
            _bound(
                "[events] pane_exited_grace_seconds must be ≤ 30.0 (FR-017); "
                f"got {overrides['pane_exited_grace_seconds']}"
            )
        )
    if overrides.get("default_page_size", defaults.default_page_size) > 50:
        raise ConfigInvalidError(
            _bound(
                "[events] default_page_size must be ≤ 50 (FR-030); "
                f"got {overrides['default_page_size']}"
            )
        )
    if overrides.get("max_page_size", defaults.max_page_size) > 50:
        raise ConfigInvalidError(
            _bound(
                "[events] max_page_size must be ≤ 50 (FR-030); "
                f"got {overrides['max_page_size']}"
            )
        )
    # FR-019 cross-check: per_cycle_byte_cap_bytes must be ≥
    # per_event_excerpt_cap_bytes; otherwise no full record can ever
    # fit (configuration.md CHK033 edge case).
    pcb = int(overrides.get("per_cycle_byte_cap_bytes", defaults.per_cycle_byte_cap_bytes))
    pee = int(overrides.get("per_event_excerpt_cap_bytes", defaults.per_event_excerpt_cap_bytes))
    if pcb < pee:
        raise ConfigInvalidError(
            _bound(
                f"[events] per_cycle_byte_cap_bytes ({pcb}) must be ≥ "
                f"per_event_excerpt_cap_bytes ({pee})"
            )
        )

    fields = {f: getattr(defaults, f) for f in defaults.__dataclass_fields__}
    fields.update(overrides)
    return EventsConfig(**fields)  # type: ignore[arg-type]


def write_default_config(config_file: Path, *, namespace_root: Path | None = None) -> str:
    """Write the default config at *config_file* if absent.

    Returns ``"created"`` when this call wrote the file, ``"already initialized"``
    when it was already present (and had an acceptable mode).
    Raises ``OSError`` on filesystem errors or pre-existing weak modes.
    """
    if namespace_root is None:
        namespace_root = config_file.parent

    _ensure_dir_chain(config_file.parent, namespace_root=namespace_root)

    if config_file.exists():
        _verify_file_mode(config_file, _FILE_MODE)
        return "already initialized"

    flags = os.O_WRONLY | os.O_CREAT | os.O_EXCL
    fd = os.open(config_file, flags, _FILE_MODE)
    try:
        os.write(fd, _render_default_config().encode("utf-8"))
        os.fchmod(fd, _FILE_MODE)
    finally:
        os.close(fd)
    return "created"
