// T031 — i18n wiring (research R-08 + R-23).
//
// `MaterialApp` consumes `AppLocalizations.delegate` (generated by
// `flutter gen-l10n` from `assets/l10n/en.arb` per `l10n.yaml`) plus the
// standard flutter_localizations delegates.
//
// This file exports the convenience that other layers import — but until
// `flutter gen-l10n` is run by the operator (post-T009), the generated
// `app_localizations.dart` file doesn't exist on disk. To keep this file
// from breaking the analyzer pre-codegen, we re-export only the wiring
// helpers; the actual `AppLocalizations` import lives in `app.dart`.

import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';

/// Standard localization delegates for `MaterialApp.localizationsDelegates`.
/// `AppLocalizations.delegate` (codegen output) is added separately in `app.dart`.
const List<LocalizationsDelegate<dynamic>> baseLocalizationDelegates = [
  GlobalMaterialLocalizations.delegate,
  GlobalWidgetsLocalizations.delegate,
  GlobalCupertinoLocalizations.delegate,
];

/// Per R-23 + FR-067: English-only at MVP, layer in place for future locales.
const List<Locale> supportedLocales = [Locale('en')];
