import 'package:agenttower_control_panel/core/config/settings_model.dart';
import 'package:agenttower_control_panel/core/daemon/app_client.dart';
import 'package:agenttower_control_panel/core/daemon/session.dart';
import 'package:agenttower_control_panel/core/daemon/socket_client.dart';
import 'package:agenttower_control_panel/core/l10n/app_localizations.dart';
import 'package:agenttower_control_panel/core/l10n/l10n_wiring.dart';
import 'package:agenttower_control_panel/core/providers.dart';
import 'package:agenttower_control_panel/domain/models/common_enums.dart'
    as enums;
import 'package:agenttower_control_panel/features/agent_ops/dashboard/dashboard_view.dart';
import 'package:agenttower_control_panel/features/project_specs/projects/projects_view.dart';
import 'package:agenttower_control_panel/features/project_specs/providers.dart'
    as project_providers;
import 'package:agenttower_control_panel/features/settings/providers.dart'
    as settings_providers;
import 'package:agenttower_control_panel/features/settings/settings_view.dart';
import 'package:agenttower_control_panel/features/shell/runtime_state_provider.dart';
import 'package:agenttower_control_panel/features/testing_demo/available_validation/available_validation_view.dart';
import 'package:agenttower_control_panel/ui/theme/color_tokens.dart';
import 'package:alchemist/alchemist.dart';
import 'package:flutter/material.dart' as m;
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../helpers/fixture_builders.dart';

/// T151 — Golden tests for every workspace top-level view across the
/// FR-066 Light / Dark / System theme axis and the FR-009 Comfortable /
/// Compact density axis.
///
/// Surfaces covered (one alchemist [goldenTest] per surface, 6 scenarios
/// per file):
///   * Agent Operations  → Dashboard           (`dashboard.png`)
///   * Project & Specs   → Projects            (`projects.png`)
///   * Testing & Demo    → Available Validation (`available_validation.png`)
///   * Settings          → main Settings view  (`settings.png`)
///
/// Each scenario is the cross-product of:
///   { ThemeMode.light, ThemeMode.dark, ThemeMode.system-as-light } ×
///   { DensityMode.comfortable, DensityMode.compact }
/// → 6 scenarios per surface × 4 surfaces = 24 captured panes total.
///
/// Goldens are generated by the operator via
/// `flutter test --update-goldens test/golden/workspace_goldens_test.dart`.
/// This file is committed with the test code only; the golden PNGs land
/// under `test/golden/goldens/` (alchemist default) once the operator
/// runs the update step.
///
/// Hard rules (per T151):
///   * Test code only — no `lib/` mutations.
///   * `test/helpers/fixture_builders.dart` is used as-is.
void main() {
  m.WidgetsFlutterBinding.ensureInitialized();

  goldenTest(
    'Agent Operations → Dashboard renders across theme × density',
    fileName: 'dashboard',
    builder: () => GoldenTestGroup(
      columns: 2,
      children: [
        for (final variant in _variants)
          GoldenTestScenario(
            name: variant.label,
            constraints: const m.BoxConstraints.tightFor(
              width: 1200,
              height: 800,
            ),
            child: _wrapped(
              variant: variant,
              overrides: [
                appClientProvider.overrideWithValue(
                  _FakeAppClient(
                    dashboardResult: Fixtures.dashboardResult(
                      containersActive: 3,
                      panesTotal: 12,
                      panesRegistered: 7,
                      panesUnregistered: 5,
                      agentsTotal: 4,
                      agentsByRole: const {
                        'master': 2,
                        'slave': 2,
                      },
                      logAttachmentsActive: 4,
                      eventsTotal: 99,
                      queueQueued: 1,
                      queueBlocked: 2,
                      queueDelivered: 50,
                      routesEnabled: 3,
                      routesDisabled: 1,
                    ),
                  ),
                ),
                runtimeStateProvider.overrideWith(
                  () => _StubRuntimeNotifier(
                    const RuntimeState(
                      kind: enums.RuntimeStateKind.runtimeHealthyPopulated,
                      daemonVersion: '0.1.0',
                    ),
                  ),
                ),
              ],
              child: const DashboardView(),
            ),
          ),
      ],
    ),
  );

  goldenTest(
    'Project & Specs → Projects renders across theme × density',
    fileName: 'projects',
    builder: () => GoldenTestGroup(
      columns: 2,
      children: [
        for (final variant in _variants)
          GoldenTestScenario(
            name: variant.label,
            constraints: const m.BoxConstraints.tightFor(
              width: 1200,
              height: 800,
            ),
            child: _wrapped(
              variant: variant,
              overrides: [
                appClientProvider.overrideWithValue(
                  _FakeAppClient(
                    projectListResult: PagedResult(
                      items: [
                        Fixtures.project(
                          projectId: 'proj-1',
                          label: 'AgentTower',
                          repositoryPath: '/work/agenttower',
                          branchName: 'main',
                          primaryMasterAgentIds: const ['claude-master-1'],
                          activeFeatureChangeId: 'FEAT-012',
                          validationKind: 'green',
                          attentionSeverity: 'warning',
                          attentionOpenCount: 2,
                          unreadNotificationCount: 3,
                          subAgentCount: 4,
                        ),
                        Fixtures.project(
                          projectId: 'proj-2',
                          label: 'opensoft-frontend',
                          repositoryPath: '/work/opensoft-frontend',
                          branchName: 'feature/header-redesign',
                          primaryMasterAgentIds: const [
                            'codex-master-1',
                            'gemini-master-1',
                          ],
                          driftSeverity: 'warning',
                          driftOpenCount: 1,
                          validationKind: 'red',
                          attentionSeverity: 'high',
                          attentionOpenCount: 5,
                        ),
                      ],
                      cursorNext: null,
                      total: 2,
                    ),
                  ),
                ),
                runtimeStateProvider.overrideWith(
                  () => _StubRuntimeNotifier(
                    const RuntimeState(
                      kind: enums.RuntimeStateKind.runtimeHealthyPopulated,
                      daemonVersion: '0.1.0',
                    ),
                  ),
                ),
              ],
              child: const ProjectsView(),
            ),
          ),
      ],
    ),
  );

  goldenTest(
    'Testing & Demo → Available Validation renders across theme × density',
    fileName: 'available_validation',
    builder: () => GoldenTestGroup(
      columns: 2,
      children: [
        for (final variant in _variants)
          GoldenTestScenario(
            name: variant.label,
            constraints: const m.BoxConstraints.tightFor(
              width: 1200,
              height: 800,
            ),
            child: _wrapped(
              variant: variant,
              overrides: [
                appClientProvider.overrideWithValue(
                  _FakeAppClient(
                    validationEntrypointListResult: PagedResult(
                      items: [
                        Fixtures.validationEntrypoint(
                          entrypointId: 'ep-unit',
                          label: 'Run unit tests',
                          type: 'unit_test',
                          description:
                              'Run the project unit-test suite (pytest).',
                          blockingLevel: 'required',
                        ),
                        Fixtures.validationEntrypoint(
                          entrypointId: 'ep-lint',
                          label: 'Lint + format check',
                          type: 'lint',
                          description:
                              'ruff + black --check across the repo.',
                          blockingLevel: 'recommended',
                          estimatedDurationMs: 5000,
                        ),
                        Fixtures.validationEntrypoint(
                          entrypointId: 'ep-demo',
                          label: 'Demo smoke test',
                          type: 'integration_test',
                          description: 'End-to-end demo readiness scenario.',
                          blockingLevel: 'informational',
                          recommendedWhen:
                              'Before opening a demo PR for stakeholder review.',
                          estimatedDurationMs: 120000,
                        ),
                      ],
                      cursorNext: null,
                      total: 3,
                    ),
                  ),
                ),
                runtimeStateProvider.overrideWith(
                  () => _StubRuntimeNotifier(
                    const RuntimeState(
                      kind: enums.RuntimeStateKind.runtimeHealthyPopulated,
                      daemonVersion: '0.1.0',
                    ),
                  ),
                ),
                // Available Validation early-returns "No project selected"
                // unless a project id is in scope — pre-select proj-1 so
                // the populated entrypoint list renders.
                project_providers.selectedProjectIdProvider
                    .overrideWith((ref) => 'proj-1'),
              ],
              child: const AvailableValidationView(),
            ),
          ),
      ],
    ),
  );

  goldenTest(
    'Settings renders across theme × density',
    fileName: 'settings',
    builder: () => GoldenTestGroup(
      columns: 2,
      children: [
        for (final variant in _variants)
          GoldenTestScenario(
            name: variant.label,
            constraints: const m.BoxConstraints.tightFor(
              width: 1200,
              height: 800,
            ),
            child: _wrapped(
              variant: variant,
              overrides: [
                appClientProvider.overrideWithValue(_FakeAppClient()),
                runtimeStateProvider.overrideWith(
                  () => _StubRuntimeNotifier(
                    const RuntimeState(
                      kind: enums.RuntimeStateKind.runtimeHealthyPopulated,
                      daemonVersion: '0.1.0',
                    ),
                  ),
                ),
                // The real SettingsNotifier reads SettingsRepository in its
                // build() which itself reads UxStateRepository — neither
                // is wired in a widget test. Substitute a stub Notifier
                // that yields a known-good Settings derived from the
                // variant so the theme/density toggle chips render in
                // their selected state.
                settings_providers.settingsProvider
                    .overrideWith(() => _StubSettingsNotifier(variant.toSettings())),
              ],
              child: const SettingsView(),
            ),
          ),
      ],
    ),
  );
}

// =========================================================================
// Variant axis (3 themes × 2 densities = 6).
// =========================================================================

class _Variant {
  const _Variant({
    required this.theme,
    required this.density,
  });

  final enums.ThemeMode theme;
  final enums.DensityMode density;

  String get label => '${theme.wireValue} · ${density.wireValue}';

  /// Material's [m.ThemeMode]. `system` is mapped to the same
  /// brightness Light produces so the golden encodes a deterministic
  /// image (no host-OS dependency).
  m.ThemeMode get materialThemeMode => switch (theme) {
        enums.ThemeMode.light => m.ThemeMode.light,
        enums.ThemeMode.dark => m.ThemeMode.dark,
        enums.ThemeMode.system => m.ThemeMode.light,
      };

  /// Material's [m.VisualDensity] for the density axis. Comfortable maps
  /// to the platform default; Compact maps to the densest standard preset.
  m.VisualDensity get visualDensity => switch (density) {
        enums.DensityMode.comfortable => m.VisualDensity.standard,
        enums.DensityMode.compact => m.VisualDensity.compact,
      };

  Settings toSettings() => Settings(
        daemonSocketPath: '/var/run/agenttower/app.sock',
        theme: theme,
        density: density,
        notificationsGrouping: true,
        osNativeNotifications: false,
        debugLogging: false,
      );
}

const _variants = <_Variant>[
  _Variant(theme: enums.ThemeMode.light, density: enums.DensityMode.comfortable),
  _Variant(theme: enums.ThemeMode.light, density: enums.DensityMode.compact),
  _Variant(theme: enums.ThemeMode.dark, density: enums.DensityMode.comfortable),
  _Variant(theme: enums.ThemeMode.dark, density: enums.DensityMode.compact),
  _Variant(theme: enums.ThemeMode.system, density: enums.DensityMode.comfortable),
  _Variant(theme: enums.ThemeMode.system, density: enums.DensityMode.compact),
];

/// Wraps a workspace view in a [ProviderScope] + [m.MaterialApp] configured
/// for the given variant, so each scenario gets its own themed shell.
m.Widget _wrapped({
  required _Variant variant,
  required List<Override> overrides,
  required m.Widget child,
}) {
  final lightTheme = ColorTokens.light().copyWith(
    visualDensity: variant.visualDensity,
  );
  final darkTheme = ColorTokens.dark().copyWith(
    visualDensity: variant.visualDensity,
  );
  return ProviderScope(
    overrides: overrides,
    child: m.MaterialApp(
      debugShowCheckedModeBanner: false,
      theme: lightTheme,
      darkTheme: darkTheme,
      themeMode: variant.materialThemeMode,
      localizationsDelegates: const [
        ...baseLocalizationDelegates,
        AppLocalizations.delegate,
      ],
      supportedLocales: supportedLocales,
      home: m.Scaffold(body: child),
    ),
  );
}

// =========================================================================
// Stubs (Riverpod overrides). Mirrors the shape used by the existing
// widget tests under `test/features/agent_ops/dashboard/`.
// =========================================================================

class _StubRuntimeNotifier extends RuntimeStateNotifier {
  _StubRuntimeNotifier(this._state);
  final RuntimeState _state;
  @override
  RuntimeState build() => _state;
}

class _StubSettingsNotifier extends settings_providers.SettingsNotifier {
  _StubSettingsNotifier(this._initial);
  final Settings _initial;
  @override
  Settings build() => _initial;
}

/// Minimal [AppClient] stand-in. Each test overrides only the methods
/// the surface under test actually calls; everything else falls back to
/// `super`'s real implementation, which will throw if invoked (the
/// underlying [SocketClient] points at a path that will never bind).
/// That throw-on-misuse is intentional — it surfaces "this golden test
/// hit a method we forgot to fake" loudly rather than spinning forever.
class _FakeAppClient extends AppClient {
  _FakeAppClient({
    Map<String, dynamic>? dashboardResult,
    PagedResult? projectListResult,
    PagedResult? validationEntrypointListResult,
  })  : _dashboardResult = dashboardResult ?? Fixtures.dashboardResult(),
        _projectListResult = projectListResult ??
            const PagedResult(
              items: <Map<String, dynamic>>[],
              cursorNext: null,
              total: 0,
            ),
        _validationEntrypointListResult = validationEntrypointListResult ??
            const PagedResult(
              items: <Map<String, dynamic>>[],
              cursorNext: null,
              total: 0,
            ),
        super(
          session: DaemonSession(
            client: SocketClient('/nonexistent/never-bound.sock'),
          ),
        );

  final Map<String, dynamic> _dashboardResult;
  final PagedResult _projectListResult;
  final PagedResult _validationEntrypointListResult;

  @override
  Future<Map<String, dynamic>> dashboard({int recentLimit = 10}) async =>
      _dashboardResult;

  @override
  Future<PagedResult> projectList({String? cursorNext, int? limit}) async =>
      _projectListResult;

  @override
  Future<PagedResult> validationEntrypointList({
    String? cursorNext,
    int? limit,
    String? projectId,
    String? scopeKind,
    bool? enabled,
  }) async =>
      _validationEntrypointListResult;
}
